### ISSUE TITLE
React & Redux group project: set up our Kanban board

### ISSUE THREAD

**Issue by MahdiAghaali** [Shedrack-Sunday/Space-Travelers-Hub#25]
Hello, this is the Issue for the code review of our Kanban board.
There are 2 people on the team:

1. @Shedrack-Sunday 
2. @MahdiAghaali 

here is the [link](https://github.com/Shedrack-Sunday/Space-Travelers-Hub/projects/1) to our project:
https://github.com/Shedrack-Sunday/Space-Travelers-Hub/projects/1

**Comment by descholar-ceo** [comment]
Hi @MahdiAghaali && @Shedrack-Sunday 🤝 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
👍🏽 The cards are covering all requirements ✔️ 
:+1: The cards are shared equitably ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
